### ISSUE TITLE
Feature request: expand selection

### ISSUE THREAD

**Issue by wmaurer** [dbankier/vscode-quick-select#1]
I really like this extension. It's great for quickly selecting and changing the contents of the string, object literal, array, etc. 

I'd also like to be able to efficiently use it to also cut or copy a string, object literal or array. That means also selecting the opening and closing quote, curly bracket or square bracket. Your extension selects the inner not the outer.

Rather than having a whole set of commands to select the outer as well as the inner, it would be useful to have a command that extends the current inner selection to include the outer, i.e. extending the selection one to the left and one to the right.

What do you think? I could also make a PR if you would like ...

**Comment by dbankier** [comment]
Yes. I was already thinking of using the equivalent closing bracket, etc as
the shortcut. It would be simple to implement if you have a look at the
source. Not sure what to use as a sensible shortcut for quotes. Or were you
thinking of using a separate common shortcut to expand a character and /or
tag?

It's late here now. I will look at it tomorrow.

**Comment by wmaurer** [comment]
My original thought was a separate common shortcut, but it would be useful to also have the commands implemented for doing the 'outer select' in one step. I would suggest implementing the commands for both possibilities.

WRT keybindings, I had to map them myself anyway because:
* on Windows it's ctrl, not cmd
* VSCode doesn't play well with international keyboard layouts

**Comment by dbankier** [comment]
Ok. Will fix the keybindings as well to make to x-platorm

**Comment by dbankier** [comment]
Ok. Added quite a bit. Now supports multi-lines, windows shortcuts, back-ticks etc.
Just need to add the expansion shortcut for quote selection.

**Comment by wmaurer** [comment]
Thanks a lot, it looks good.
For quote selection, I've got no real sensible suggestion for a shortcut, but could you implement the commands anyway, even if you don't implement a default keybinding? That way users can still map to whatever makes sense to them if they want to.
