### ISSUE TITLE
toggling " to ' stopped working in vscode 1.17

### ISSUE THREAD

**Issue by jeremychone** [dbankier/vscode-quick-select#10]
The toggle `"` <-> `'` with `⌘k ;` stopped working with vscode 1.17. It was working fine in 1.16.

The rest seems to work.

**Comment by lleolin** [comment]
In my case it hasn't completely stopped working, it's just that it only changes the quote at the cursor position instead of both surrounding quotes.

**Comment by jeremychone** [comment]
@lleolin yes, correct, it only change one quote.

**Comment by dbankier** [comment]
Thanks. I will look at this next week.

**Comment by dbankier** [comment]
Just tried it. The default shortcut is `⌘k :` not `⌘k ;`. Seems to work for me...

**Comment by dbankier** [comment]
Yes broken in 1.17. Working on it.

**Comment by dbankier** [comment]
new version published
