### ISSUE TITLE
Replacing single/double quotes with backtick

### ISSUE THREAD

**Issue by hgezim** [dbankier/vscode-quick-select#14]
I often have to change single-quoted strings to back tick ones. I still haven't found a painless wait to do that with this plugin.

Ideas?

**Comment by garetmckinley** [comment]
Have you found a plugin that is capable of this? Quick replacement of quotes is one of the biggest vim features I miss.

**Comment by dbankier** [comment]
done

**Comment by DanKaplanSES** [comment]
If this is already implemented, the readme doesn't mention it as a feature. Maybe it's out of date. How does this feature work though? Does the toggle shortcut iterate between single, double, and backtick quotes?
