### ISSUE TITLE
Selecting inside back tick adds unwanted backtick

### ISSUE THREAD

**Issue by mikaoelitiana** [dbankier/vscode-quick-select#17]
I use this extension for my daily job and I love it. 

One issue I often encounter is when I want to select inside backtick with default shortcut (``cmd+K ` ``), the content is selected but an **unwanted new backtick is added**. 

See the animation below:

![backtick](https://user-images.githubusercontent.com/674667/43587760-3e3511f8-966b-11e8-9dd3-c472d0bd452b.gif)

**Comment by dbankier** [comment]
can't replicate it at the moment
