### ISSUE TITLE
Suggestion: show commands in palette

### ISSUE THREAD

**Issue by OliverJAsh** [dbankier/vscode-quick-select#22]
I often have to refer back to this repository to remember what the commands and shortcuts are. It would be very useful if all of the commands this extension provides were added to the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette), so they are more easily discovered.

**Comment by katerlouis** [comment]
+1
I often forget shortcuts and find myself opening command palette and just typing "Quick Select" in hope to find all commands there;
