### ISSUE TITLE
Switch between single and double quote  

### ISSUE THREAD

**Issue by okian** [dbankier/vscode-quick-select#3]
It would be great if we could switch between single and double quotes. for example `'some string'` to `"some string"` and vise versa.
I understand it's may not looks like relevant to the purpose of this extension but most of the times the reason of selecting strings is just changing ' or " quotes.

**Comment by dbankier** [comment]
Yep. I like the idea. Should be simple to implement. I had that the other day when wanting to change an json object to array.

 I just need to think through the flow. 
For example, <kbd>ctrl</kbd> + <kbd>"</kbd> highlights the text inside the quotes (like it does now). Then if followed by  <kbd>ctrl</kbd> + <kbd>'</kbd>, since there is already a selection, it replaces the `"` to `'`. 

Sound good?

**Comment by moostad** [comment]
I think we don't need to specify two combinations of keys and it's better to think it just as string. I mean for example ```ctrl```+```'``` ( ```"``` needs to holding ```shift``` too )  select both ```'string'```  and ```"string"``` and pressing ```ctrl```+```'``` again will switch between single and double quotes and so on. this idea can expand to other functionalities, I mean why we need two different key for selecting inner and outer? I personally prefer to pressing once to select inner and pressing it again to select outer (and pressing again expand to parent inner) and ideally the other key doing it reverse (from outer to inner)  it's easier to remember and much efficient for using remaining keys on keyboard. ;)

**Comment by dbankier** [comment]
hmm... I hear.

**Comment by fronteed** [comment]
Here's the same plugin for Sublime https://github.com/colinta/SublimeChangeQuotes

> You can put your cursor inside the text that is in quotes and then execute the command to replace the quotes. No selection needed. Works with `cmd+shift+'` by default.

Hope this can also be adopted for vscode.

**Comment by fronteed** [comment]
Here's the same plugin for Sublime https://github.com/colinta/SublimeChangeQuotes

> You can put your cursor inside the text that is in quotes and then execute the command to replace the quotes. No selection needed. Works with `cmd+shift+'` by default.

Hope this can also be adopted for vscode.

**Comment by wmaurer** [comment]
There's another extension available which allows to switch between single and double quotes:
https://marketplace.visualstudio.com/items?itemName=vilicvane.es-quotes

**Comment by wprater** [comment]
would be nice if there were a more universal feature to swap single <-> double quotes in all text grammars.

**Comment by mioo** [comment]
Here's the same plugin for sublime https://github.com/spadgos/sublime-ToggleQuotes

> Make one or more selections of strings including their quotes and then press the opposite quote mark. That is, if you have "test" press ', if you have 'test', press ".

**Comment by anlek** [comment]
I'd love to see `sublime-ToggleQuotes` in vsCode!

**Comment by dbankier** [comment]
This is now fixed and published. You will probably want to change the shortcuts...

**Comment by anlek** [comment]
This is a great step forward, thank you!

Any chance to not move the caret to the end of the string?

**Comment by dbankier** [comment]
Sure.  Will do.

**Comment by anlek** [comment]
Just tested it, it works like a dream! Thank you so much!

**Comment by Ciantic** [comment]
I would like to toggle also between backticks (\`) since those are required for variable substitution in JavaScript, e.g. 
```
`string text ${variable} string text`
```

My suggestion is to not add a new command, but make it cycle between all three quote styles ", ' and `

**Comment by almadsen** [comment]
How to use it, cause I can't find anything about it in vs code?

**Comment by raldred** [comment]
Don't think this works on recent Vscode.
<kbd>Cmd</kbd> + <kbd>k</kbd> then <kbd>'</kbd> doesn't do anything in my documents.

**Comment by raldred** [comment]
@almadsen Press <kbd>cmd</kbd> + <kbd>k</kbd> then <kbd>;</kbd>

**Comment by doplumi** [comment]
@raldred I've got the last version and I got 
![schermata 2017-05-21 alle 17 33 39](https://cloud.githubusercontent.com/assets/4347084/26285217/c00fa57c-3e4b-11e7-9c4d-92e933b2b163.png)

You sure that's it?

**Comment by Ciantic** [comment]
Just set the shortcut yourself? I think the action required for mapping is called `extension.switchQuotes` mentioned in the readme.

**Comment by koskoci** [comment]
I can't get this to work. Do I need to install an extension? Thanks!

**Comment by dbankier** [comment]
@koskoci this is an extension. Search for "Quick and Simple Text Selection"

**Comment by koskoci** [comment]
@dbankier Thanks, works like a charm!

**Comment by batamire** [comment]
@doplumi release CMD after CMD+K, before ;

**Comment by garetmckinley** [comment]
Have you thought about adding the ability to change to backticks? I primarily use JavaScript, and in the era of ES6, I find myself having to utilize all 3 methods of quotes quite often and have yet to find a plugin that allows changing to backticks. I feel like this plugin is 90% of the way there

**Comment by raldred** [comment]
Pretty sure it's a simple addition. Create a PR maybe?

**Comment by garetmckinley** [comment]
@raldred yeah for sure, I was mainly asking if it was something that was considered or even wanted with this plugin. I don't wanna put in time adding it if it doesn't align with the goal of the plugin

**Comment by kristofmulier** [comment]
I always get this:
```
The key combination (Ctrl+K, Ctr+K) is not a command.
```
Whatever I try:

![image](https://user-images.githubusercontent.com/19362684/140489497-e7f9372f-ca7b-4c43-951b-37adbda023ad.png)

I'm working on Windows 10 with the latest version of VSCode (`v1.62.0`) and latest version of the **Quick and Simple Text Selection** plugin (`v0.2.9`)
