### ISSUE TITLE
Include backtick as regular quotes

### ISSUE THREAD

**Issue by DavidBabel** [dbankier/vscode-quick-select#5]
Hey hi !

Just discover your extension and it's amazing !

It will be great if the backtick was affected by the `selectEitherQuote` and the `switchQuotes` options.
allowing a loop " => ' => \` => " => ' => \`

**Comment by dbankier** [comment]
done.

**Comment by DavidBabel** [comment]
great !

**Comment by maxrothman** [comment]
This is annoying to use in languages that don't support backticks as quotes (i.e. most of them). Could it be made configurable, or auto-detect by language? Even adding a special case for a few languages would be an improvement.
