### ISSUE TITLE
can't get this to work :(

### ISSUE THREAD

**Issue by jamesdixon** [dbankier/vscode-quick-select#6]
Hi, I installed your extension, both manually and then through the GUI, but no luck :( I'm running VSCode 1.12.2. Any ideas?

Thank you!

**Comment by leocaseiro** [comment]
Hi, I as having the same issue, so I changed the key bindings myself and it's working now!

Check on your `keybindings.json` if you have the shortcuts. You can customize with other shortcuts (the default ones weren't working for me).

On mac, go to Code -> Preferences -> Keyboard Shortcuts

<img width="588" alt="screen shot 2017-10-06 at 12 22 43 pm" src="https://user-images.githubusercontent.com/940070/31259339-b5054134-aa91-11e7-9cd0-639a6f1b02ef.png">



Try search for `extension.select` and see if they are there:
<img width="965" alt="screen shot 2017-10-06 at 12 24 31 pm" src="https://user-images.githubusercontent.com/940070/31259338-b2acfc6a-aa91-11e7-95fc-7a9ad8ee77d3.png">

Try change with different keybindings clicking at the edit pencil.
