### ISSUE TITLE
Selecting multi-line tag content doesn't work

### ISSUE THREAD

**Issue by mikaoelitiana** [dbankier/vscode-quick-select#9]
When I select tag content with `cmd + k >`, it works only for single line tags. Multi-line tag contents are not selected. 

![multi-line-tag-content](https://user-images.githubusercontent.com/674667/30796850-74143490-a1dc-11e7-8b83-cb76c2c0b2bc.gif)

**Comment by chrislandeza** [comment]
ping @dbankier
